---
title: "Publication Bias - Meta-Analysis"
output: html_notebook
---

```{r}
# Load dataset
suppressWarnings(suppressMessages({
    library(tidyverse)
    library(metafor)
}))
```

```{r}
# Load dataset
suppressWarnings(suppressMessages({
    datacsv <- read_csv("datasets/irrt1vt2_estBD_june23.csv")
    dataset <- data.frame(datacsv)
}))

# Remove outliers
temp_dataset <- split(dataset, dataset$ref_num=="24")
dataset <- temp_dataset$'FALSE'

# Store rows without N+ and N- pairings in a temporary variable
tempData1a <- split(dataset, dataset$N_pair=="no")
dataseta <- tempData1a$'TRUE'

# For rows that do have a N+ and N- paring, store only the N- rows in a temporary variable
tempData1b <- split(dataset, dataset$N_pair_state=="N+")
datasetb <- tempData1b$'FALSE'

# Combine the two temporary variables into a unified dataset without the N+ treatments where such pairings exist in the dataset
dataset <- rbind(dataseta, datasetb)

dataset$irrig_water_type[dataset$irrig_water_type == "sewage"] <- "waste"
dataset$irrig_water_type[dataset$irrig_water_type == "mixed"] <- "waste"

temp_dataset <- split(dataset, dataset$irrig_water_type=="waste")
dataset <- temp_dataset$'FALSE'

```

```{r}
# Calculate the effect size using the metafor package for the whole dataset including all depth increments
my_data <- escalc(n1i = organic_C_n_t1, n2i = organic_C_n_t2, m1i = organic_C_st_t1, m2i = organic_C_st_t2, 
    sd1i = organic_C_st_sd_t1, sd2i = organic_C_st_sd_t2, data = dataset, measure = "MD", 
    append = TRUE)

#ma_model_1 <- rma(yi, vi, data = my_data)
```

```{r}
fsn(yi, vi, data=my_data, type="Rosenberg")
```




