---
title: "R Notebook"
output: html_notebook
---

```{r}
    library(tidyverse)
    library(metafor)
```

```{r}
    datacsv <- read_csv("datasets/irrt1vt2_estBD_june23.csv")
    dataset <- data.frame(datacsv)
```

```{r}
# Factor dataset
dataset[sapply(dataset, is.character)] <- lapply(dataset[sapply(dataset, is.character)], as.factor)

# Store rows without N+ and N- pairings in a temporary variable
tempData1a <- split(dataset, dataset$N_pair=="no")
dataseta <- tempData1a$'TRUE'

# For rows that do have a N+ and N- paring, store only the N- rows in a temporary variable
tempData1b <- split(dataset, dataset$N_pair_state=="N+")
datasetb <- tempData1b$'FALSE'

# Combine the two temporary variables into a unified dataset without the N+ treatments where such pairings exist in the dataset
dataset <- rbind(dataseta, datasetb)

# Separate out the 0 - 10 cm depth incrememt
tempData2 <- split(dataset, dataset$depth_category=="0-10cm")
depth_10 <- tempData2$'TRUE'
```

```{r}
my_data_C <- escalc(n1i = organic_C_n_t1, n2i = organic_C_n_t2, m1i = organic_C_t1, m2i = organic_C_t2, 
    sd1i = organic_C_t1_sd_calc, sd2i = organic_C_t2_sd_calc, data = dataset, measure = "MD", 
    append = TRUE)

ma_model <- rma(yi, vi, data = my_data_C)
trim_model <- trimfill(ma_model)
summary(ma_model)
summary(trim_model)
```

```{r}
funnel(ma_model_3)
funnel(trim_model_3)
```
