---
title: "Meta-Analysis Forest Plot"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
# Load dataset
suppressWarnings(suppressMessages({
    datacsv <- read_csv("datasets/irrt1vt2_estBD_apr6.csv")
    dataset <- data.frame(datacsv)
}))
```

<b>Note:</b> There are a couple of massive outliers in the dataset, 5 - 10x the change in OC seen in any other study.  Thes rows of data have been removed from the dataset.

```{r}
# Remove outliers
temp_dataset <- split(dataset, dataset$ref_num=="24")
dataset <- temp_dataset$'FALSE'

temp_dataset <- split(dataset, dataset$ref_num=="19")
dataset <- temp_dataset$'FALSE'
```

```{r}
# Factor whole dataset
dataset[sapply(dataset, is.character)] <- lapply(dataset[sapply(dataset, is.character)], as.factor)

# Store rows without N+ and N- pairings in a temporary variable
tempData1a <- split(dataset, dataset$N_pair=="no")
dataseta <- tempData1a$'TRUE'

# For rows that do have a N+ and N- paring, store only the N- rows in a temporary variable
tempData1b <- split(dataset, dataset$N_pair_state=="N+")
datasetb <- tempData1b$'FALSE'

# Combine the two temporary variables into a unified dataset without the N+ treatments where such pairings exist in the dataset
dataset <- rbind(dataseta, datasetb)

# Split Africa dataset by Depth
d <- dataset %>% group_split(depth_cat_2)
d10 <- as.data.frame(d[1])
d20 <- as.data.frame(d[2])
d30 <- as.data.frame(d[3])
d30p <- as.data.frame(d[4])
```

```{r}
p <- ggboxplot(dataset, x="depth_cat_2", y="per_OC_change", 
          color = "soil_texture", palette = c("#00AFBB", "#E7B800", "#71f442", "#fc79e6"),
          #order = c("Hyper Arid", "Arid", "Semi-Arid", "Dry sub-humid", "Humid"),
          ylab = "% Organic Carbon Change", xlab = "Depth Category")
p + stat_summary(fun.data = give.n, geom = "text", fun = median, position = position_nudge(y = 0.5)) + theme(axis.text.x = element_text(angle = 60, hjust = 1))
```